spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
ai:
  aws:
    bedrock:
      region: us-east-1
cloud:
  aws:
    s3:
      bucket: upcycling-bucket
    stack:
      auto: false
    region:
      static: ap-northeast-2
    cloudfront:
        domain: d23fpzkzsmv7d3.cloudfront.net